services:
  - type: web
    name: pepcheck-api
    runtime: python
    plan: free
    buildCommand: pip install -r backend/app/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
